apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-tool
  template:
    metadata:
      labels:
        app: ip-tool
    spec:
      serviceAccountName: ip-tool-sa
      containers:
      - name: ip-tool
        image: "{{CONTAINER_IMAGE}}"
        imagePullPolicy: Always
        env:
        - name: MODE
          value: "collection"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"