apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-tool-deployment
  labels:
    app: ip-tool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ip-tool
  template:
    metadata:
      labels:
        app: ip-tool
    spec:
      containers:
      - name: ip-tool
        image: docker.my.registry/devops-task/ip-tool:latest
        ports:
        - containerPort: 80
        env:
        - name: EMAIL_SENDER
          value: "your_email@example.com"
        - name: EMAIL_PASSWORD
          value: "your_password"
        - name: SMTP_SERVER
          value: "smtp.example.com"
        - name: AZURE_CLIENT_ID
          value: "your_azure_client_id"
        - name: AZURE_CLIENT_SECRET
          value: "your_azure_client_secret"
        - name: AZURE_TENANT_ID
          value: "your_azure_tenant_id"
        - name: AZURE_KEYVAULT_NAME
          value: "your_keyvault_name"
        - name: AZURE_STORAGE_ACCOUNT
          value: "your_storage_account"
        - name: AZURE_STORAGE_CONTAINER
          value: "ip-tool-data"
        - name: CLUSTER_NAME
          value: "your_cluster_name"
        - name: NOTIFICATION_THRESHOLD
          value: "1"
        - name: LOG_FILE_PATH
          value: "/var/log/ip-tool.log"
---
apiVersion: v1
kind: Service
metadata:
  name: ip-tool-service
spec:
  selector:
    app: ip-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer